name: AegisOps CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Backend Image
      run: docker build -t aegisops-backend ./backend

    - name: Build Frontend Image
      run: docker build -t aegisops-frontend ./frontend

    - name: ğŸ” Trivy Scan â€“ Backend Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: aegisops-backend
        severity: HIGH,CRITICAL
        exit-code: 1

    - name: âœ… Secure Build Completed
      run: echo "AegisOps DevSecOps pipeline passed â€“ Simran Anand"

